### ISSUE TITLE
Not showing up in settings or GamePigeon - iOS 13.3.1

### ISSUE THREAD

**Issue by jakecrowley** [donato-fiore/GameSeagull#23]
Installed tweak through the repo, respring, no options for the tweak in settings, nothing happens in-game. 
Running iPhone 8 iOS 13.3.1 jailbroken using unc0ver.

The tweak seems to be loading correctly in the /var/log/extensionloader.log file, however I do not have enough experience with this sort of thing to know for sure.

```
1639673653.504 f9a09c5 INFO  MessagesExtension(2265): startup
1639673653.589 f9a09c5 DEBUG MessagesExtension(2265): SafeMode path is /private/var/mobile/Containers/Data/PluginKitPlugin/C8DBD59E-0430-4128-AA8F-6F01AC41D7A1/tmp/.safemode-585CED98C085BA814A076DD4C3F072 >1639673653.593 f9a09c5 INFO  MessagesExtension(2265): Injecting /Library/MobileSubstrate/DynamicLibraries/CepheiSpringBoard.dylib
1639673653.607 f9a09c5 DEBUG MessagesExtension(2265): Injection of /Library/MobileSubstrate/DynamicLibraries/CepheiSpringBoard.dylib completed in 13 ms
1639673653.607 f9a09c5 DEBUG MessagesExtension(2265): /Library/MobileSubstrate/DynamicLibraries/CepheiSpringBoard.dylib used 272 kbytes of memory
1639673653.607 f9a09c5 INFO  MessagesExtension(2265): Injecting /Library/MobileSubstrate/DynamicLibraries/GameSeagull.dylib
1639673653.628 f9a09c5 DEBUG MessagesExtension(2265): Injection of /Library/MobileSubstrate/DynamicLibraries/GameSeagull.dylib completed in 20 ms
1639673653.628 f9a09c5 DEBUG MessagesExtension(2265): /Library/MobileSubstrate/DynamicLibraries/GameSeagull.dylib used 256 kbytes of memory
1639673653.628 f9a09c5 DEBUG MessagesExtension(2265): completed in 129 ms
```

Screenshots:
![image](https://user-images.githubusercontent.com/8465805/146415908-5db2112f-2f99-4f60-b7ed-12189c5712a1.png) ![image](https://user-images.githubusercontent.com/8465805/146415990-e85239bd-a44f-46a0-a904-a238412b19a8.png) ![image](https://user-images.githubusercontent.com/8465805/146416069-68b1aafb-bd7e-44da-a95c-fcd2ed924847.png) ![image](https://user-images.githubusercontent.com/8465805/146416168-96b32660-798d-4c72-9da8-3c22a75cd65e.png)

**Comment by jakecrowley** [comment]
I was able to modify the source to ignore the configuration parameters, rebuild, and install the tweak on my device. After doing so, the tweak was still not showing up in the settings app, however it started working in GamePigeon, confirming my theory that it was simply an issue with the configuration settings.

**Comment by donato-fiore** [comment]
Can you please check if you have `Cephei Tweak Support` installed from `https://chariz.com/` and preferenceloader (should be included with the default package manager repos)

**Comment by jakecrowley** [comment]
Cephei Tweak Support was installed but preferenceloader was not, my bad. It works now, thank you!

**Comment by Huntermyers791** [comment]
Hey. Um how do i find seagull and install it
