### ISSUE TITLE
Needs patches

### ISSUE THREAD

**Issue by zardaboi** [donato-fiore/GameSeagull#5]
I think no games are working at the moment, ive downloaded it and tested all the games and no hack worked unfortunately

**Comment by NSExceptional** [comment]
+1, not working in 8-ball, didn't try any others

**Comment by donato-fiore** [comment]
Yes I am aware of the 8 ball being bugged, and I am currently working on a fix.

**Comment by NSExceptional** [comment]
Awesome. You should really leave this open until it's fixed though so you don't get duplicate issues from other people
