### ISSUE TITLE
Extended trajectory

### ISSUE THREAD

**Issue by Alriceee** [donato-fiore/GameSeagull#54]
Extended trajectory doesn't work on ios 16 jailbreak

**Comment by JeffVu-1** [comment]
how did you get this to run on ios 16?

**Comment by JeffVu-1** [comment]
> Extended trajectory doesn't work on ios 16 jailbreak

how did you get this to run on ios 16? and on what device?

**Comment by JeffVu-1** [comment]
> Extended trajectory doesn't work on ios 16 jailbreak

I managed to edit the files and export it into a deb but im running into an error any ideas?

Jeffs-iPhone# dpkg -i "/var/mobile/Documents/export3.deb" ;
(Reading database ... 8733 files and directories currently installed.)
Preparing to unpack .../mobile/Documents/export3.deb ...
Unpacking com.fiore.gameseagull (1.6) ...
dpkg: error processing archive /var/mobile/Documents/export3.deb (--install):
 unable to create '/.DS_Store.dpkg-new' (while processing './.DS_Store'): Read-only file system
Errors were encountered while processing:
 /var/mobile/Documents/export3.deb
#                                                      
Jeffs-iPhone#

**Comment by Alriceee** [comment]
Alright @JeffVu-1 im using a rootful jailbreak, before this website got updated: https://ios.cfw.guide. All i did was add the repo, and it installed just fine.

**Comment by JeffVu-1** [comment]
> Alright @JeffVu-1 im using a rootful jailbreak, before this website got updated: https://ios.cfw.guide. All i did was add the repo, and it installed just fine. ]
> 
> EDIT: I'm using an iPhone 8 on iOS 16.5


Hmm... I'm on iphone 8 ios 15.6.1, did you use palera1n rootful method?

**Comment by Alriceee** [comment]
> > Alright @JeffVu-1 im using a rootful jailbreak, before this website got updated: https://ios.cfw.guide. All i did was add the repo, and it installed just fine. ]
> > EDIT: I'm using an iPhone 8 on iOS 16.5
> 
> Hmm... I'm on iphone 8 ios 15.6.1, did you use palera1n rootful method? Because i think i did rootless, I can try rootful and see what happens.

yes, except i used palen1x (literally no difference.) but still a rootful jailbreak, most rootless stuff doesn't work for some reason (etc, repos not being added, ALOT of tweaks not working.)

**Comment by JeffVu-1** [comment]
> > > Alright @JeffVu-1 im using a rootful jailbreak, before this website got updated: https://ios.cfw.guide. All i did was add the repo, and it installed just fine. ]
> > > EDIT: I'm using an iPhone 8 on iOS 16.5
> > 
> > 
> > Hmm... I'm on iphone 8 ios 15.6.1, did you use palera1n rootful method? Because i think i did rootless, I can try rootful and see what happens.
> 
> yes, except i used palen1x (literally no difference.) but still a rootful jailbreak, most rootless stuff doesn't work for some reason (etc, repos not being added, ALOT of tweaks not working.)

Yea ill give rootful a try thanks for explaining the process. 👍
