### ISSUE TITLE
i dont know how to use it

### ISSUE THREAD

**Issue by zaddyg** [donato-fiore/GameSeagull#7]
i downloaded it but i dont know how to actually use it

**Comment by donato-fiore** [comment]
How to use GameSeagull:
1. Jailbreak your iDevice
2. Download the latest version from the release tab on your iDevice
3. Install the .deb file and configure the settings in the settings app

**Comment by zaddyg** [comment]
> How to use GameSeagull:
> 
> 1. Jailbreak your iDevice
> 
> 2. Download the latest version from the release tab on your iDevice
> 
> 3. Install the .deb file and configure the settings in the settings app
how to u jailbreak
